# Generated by Django 5.0.1 on 2024-01-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_nombre', models.CharField(max_length=50)),
                ('d_apellidoPaterno', models.CharField(max_length=50)),
                ('d_apellidoMaterno', models.CharField(max_length=50)),
                ('d_direccion', models.CharField(max_length=150)),
                ('d_telefono', models.CharField(max_length=15)),
                ('d_correo', models.CharField(max_length=100)),
                ('d_contrasena', models.CharField(max_length=50)),
            ],
        ),
    ]
