# Generated by Django 5.0.1 on 2024-03-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_c_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionesServicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('servicio_paciente_id', models.IntegerField()),
                ('departamento_solicitante', models.IntegerField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Aprobado', 'Aprobado'), ('No Aprobado', 'No Aprobado'), ('En Proceso', 'En Proceso')], default='En Proceso', max_length=20)),
                ('comentarios', models.TextField()),
                ('fecha_aprobacion', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Aprobaciones de Servicios',
            },
        ),
        migrations.CreateModel(
            name='BitacoraDG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tabla', models.CharField(max_length=80)),
                ('usuario', models.CharField(max_length=80)),
                ('operacion', models.CharField(choices=[('Insert', 'Insert'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bitácora DG',
            },
        ),
        migrations.CreateModel(
            name='c_dispensacion',
            fields=[
                ('di_id', models.AutoField(primary_key=True, serialize=False)),
                ('di_recetaId', models.CharField(max_length=15)),
                ('di_medicamento', models.CharField(max_length=15)),
                ('di_dosis', models.CharField(max_length=15)),
                ('di_solicitados', models.CharField(max_length=15)),
                ('di_cantidad', models.CharField(max_length=100)),
                ('di_precio', models.CharField(max_length=15)),
                ('di_fecha_venta', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='c_inventario',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False)),
                ('i_codigo', models.CharField(max_length=15)),
                ('i_tipo_presentacion', models.CharField(max_length=15)),
                ('i_via_administracion', models.CharField(max_length=15)),
                ('i_cantidad', models.CharField(max_length=15)),
                ('i_precio_costo', models.FloatField(default=0)),
                ('i_precio_venta', models.FloatField(default=0)),
                ('i_numero_lote', models.CharField(max_length=15)),
                ('i_fecha_caducidad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='c_receta_medica',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_cita_id', models.CharField(max_length=15)),
                ('r_fecha_hora_registro', models.CharField(max_length=15)),
                ('r_estatus', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='c_receta_medica_detalles',
            fields=[
                ('rc_id', models.AutoField(primary_key=True, serialize=False)),
                ('rc_recetaId', models.CharField(max_length=15)),
                ('rc_medicamento', models.CharField(max_length=15)),
                ('rc_dosis', models.CharField(max_length=15)),
                ('rc_solicitados', models.CharField(max_length=15)),
                ('rc_precio', models.CharField(max_length=15)),
                ('rc_fecha_venta', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosHospitalarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Médico', 'Médico'), ('Administrativo', 'Administrativo')], max_length=20)),
                ('tipo_intervencion', models.CharField(choices=[('Cirugia', 'Cirugia'), ('Servicio de Emergencia', 'Servicio de Emergencia'), ('Hospitalización', 'Hospitalización'), ('Consulta Externa', 'Consulta Externa'), ('Servicio Maternidad', 'Servicio Maternidad'), ('Laboratorio', 'Laboratorio'), ('Palitativos', 'Palitativos'), ('Rehabilitacion', 'Rehabilitacion'), ('Psiquiatria', 'Psiquiatria'), ('Farmacia', 'Farmacia'), ('Traslados', 'Traslados')], max_length=22)),
                ('descripcion', models.TextField()),
                ('departamento_responsable_id', models.IntegerField()),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosMedicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('departamento_id', models.IntegerField()),
                ('instalacion_superior_id', models.IntegerField()),
                ('estatus', models.CharField(choices=[('Activa', 'Activa'), ('Mantenimeinto', 'Mantenimeinto'), ('Fuera de Servicio', 'Fuera de Servicio'), ('Suspendida', 'Suspendida')], max_length=20)),
            ],
        ),
    ]
